version: "3"
  
services:

  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
    - 27017:27017
    volumes:
    - /data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    
  postgres:
    container_name: postgres_stockExchange
    image: postgres:latest
    ports:
      - "5431:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin_stockExchange
    image: dpage/pgadmin4
    ports:
      - "8081:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  mongodb_data_container: